#Simple script which plot the average intensity values over time from all cells
#Uses the fluorescence intensity values generated by the imagej macro 'cp_measure_stacks.ijm'
#Used to generate figure

library(tidyverse)
library(svglite)

#Import function
f_import <- function(x){read_tsv(x,
                                 col_names = T,
                                 id="FileName")
}

#normalize function
f_normalize <- function(x){
  x/mean(x[1:6])
}


#Location of 'cp_measure_stacks.ijm' output text file
WindowsPathName <- "C:/Users/dw2471/OneDrive - cumc.columbia.edu/temp/fiji_analysis_output"
 setwd(WindowsPathName )
 tps_files <- dir(WindowsPathName,pattern = ".*analysis.txt")
 imported_data<-tps_files%>%
   map_df(.,f_import)
 
#Remove unwated columns from the data 
all_data<-imported_data %>%
select(!2:3)%>%
  rename(time_s = 2)
   
#normalize data
normalized_data = all_data%>%
mutate(across(!contains("time") & where(is.numeric),f_normalize))

#plot data
normalized_data%>%
  select(-FileName)%>%
pivot_longer(-(contains("time")))%>%
  ggplot(.,aes(x=time_s,y=value))+
  stat_summary(fun = mean, geom = "line") + 
  stat_summary(fun = mean, geom = "point") + 
  stat_summary(fun.data = mean_se, geom = "errorbar")+
  #stat_summary(fun.data = mean_se, geom = "ribbon",alpha = 0.2)+
  theme_classic()
ggsave("atp_plot.svg",width=4,height=4)



